; Copyright (C) Yagnesh Raghava Yakkala. http://yagnesh.org
;    File: yagUtils.ncl
; Created: Wednesday, September 21 2011
; License: GPL v3 or later. <http://www.gnu.org/licenses/gpl.html>
;

; Description:
; This one script is needed to load.

load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/gsn_code.ncl"
load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/gsn_csm.ncl"
load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/contributed.ncl"
load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/shea_util.ncl"
load "$NCARG_ROOT/lib/ncarg/nclscripts/wrf/WRF_contributed.ncl"
load "$nsc/WRFUserARW.ncl"

load "$nsc/is.ncl"
load "$nsc/generic.ncl"
load "$nsc/resources.ncl"
load "$nsc/anno.ncl"
load "$nsc/plot.ncl"

load "$nsc/wps.ncl"
load "$nsc/wrf.ncl"
